<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<?php 
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
 $customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
?>
<link href="//fonts.googleapis.com/css?family=Libre+Baskerville:400,400i,700&display=swap" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&subset=latin-ext" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
<header class="page-header alothemes">
    <div class="header">
		<div class="header-top">
			<ul class="header-top-link">
				<li>Currency : USD</li>
				<li>Free Shipping Over $49</li>
				<li>Member Discounts Over $99</li>
			</ul>
		</div>
		<div class="header-content menu-mobile header-sticker">
			<div class="content-logo">
				<div class="header-logo">
					<span data-action="toggle-nav" class="action nav-toggle" style="display: none;"></span>
					<?php echo $this->getChildHtml('logo'); ?>
				</div>
			</div>
			<div class="content-menu">
				<div class="header-right-menu">
					<?php echo $this->getChildHtml('navigation.sections'); ?>
					<?php echo $this->getChildHtml('catalog.topnav'); ?>
				</div>
				<div class="content-cart">
					<div class="tool-header">
						<div class="tool-account">
							<div class="account-icons toggle-tab"></div>
							<div class="toggle-content">
								<?php echo $this->getChildHtml('header.links'); ?>
							</div>
						</div>
						<?php echo $this->getChildHtml('minicart'); ?>
						<div class="search-area header-search">
							<?php echo $this->getChildHtml('top.search'); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
