<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<?php $_product = $block->getProduct() ?>
<div class="product-addto-links" data-role="add-to-links">
    <?= $block->getChildHtml() ?>
    <?php if ($block->canEmailToFriend()): ?>
        <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
        class="action mailto friend"><!-- <i class="pe-7s-mail icons"></i> --><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></a>
    <?php endif; ?>
    <?php
        $_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
        if($_aloHelper->getFreeShipping($_product)):
            ?>
            <p class="free-ship action"><i class="gokko-icon icon-truck"></i><span><?php /* @escapeNotVerified */ echo __('Free Shipping') ?></span></p>
            <?php
        endif;
    ?>
</div>
