<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product = $block->getProduct();
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <div class="actions add-to-cart">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty clearfix">
		    <div class="product-qty">
				<label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
				<div class="control custom-qty clearfix">
				    <input type="number"
						   name="qty"
						   id="qty"
						   maxlength="12"
						   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
						   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
						   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
						   />
					<div class="btn-plus">
                        <button  type="button" class="increase items" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;">
							<i class="fa fa-caret-up"></i>
						</button>					
						<button  type="button" class="reduced items" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) && qty > 1 ) result.value--;return false;">
							<i class="fa fa-caret-down"></i>
						</button> 
					</div>
				</div>
			</div>
        </div>
        <?php endif; ?>
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart button btn-cart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
        <div class="product-social-links clearfix">
			<div class="product-addto-links add-to-links clearfix" data-role="add-to-links">
				<?php $_product = $block->getProduct() ?>
				<a href="#" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
					data-role="add-to-links"
					class="action tocompare">
					<i class="icon icon-menu icons"></i><span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
				</a>
				<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
					<a href="#"
						class="action towishlist"
						data-post='<?php /* @escapeNotVerified */ echo $_wishlistSubmitParams; ?>'
						data-action="add-to-wishlist">
						<i class="icon icon-heart icons"></i><span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
					</a>
				<?php endif; ?>
				<?php if ($block->canEmailToFriend()): ?>
					<a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
					   class="action mailto friend">
					   <i class="icon icon-envelope icons"></i><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></a>
				<?php endif; ?>
			</div>
		</div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
