<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
$_helper = $this->helper('Mageplaza\SocialLogin\Helper\Config');
?>
<style>
    .page-title-wrapper
    {
        font-size: 20px;
        text-align: center;
        padding-bottom: 22px;
        color: #000;
        font-size: 56px;
        font-weight: 500;
        border-bottom: 4px solid #000;
        text-align: center;
    }
    .form-create-account
    {
        margin-top:20px;

    }
    .terms-box {
        height: 300px;
        overflow-y: scroll;
        margin-top: 20px;
        border: 1px solid #ccc;
    }

</style>
<?php echo $block->getChildHtml('form_fields_before')?>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.register.extra')?>

<style>
.legend
{
    font-size: 16px;
    font-weight: 500;
    margin-bottom: 12px;
}
.register-container
{
    padding-left: 40px;
    padding-right: 40px;
}
.field
{
    padding-bottom: 15px;
}
.label
{
    font-size: 14px;
}
.user-agreements-checkboxes
{
    margin-top: 10px;
    margin-bottom: 20px;
}

customer-account-create .user-agreements-checkboxes, .customer-account-login .user-agreements-checkboxes {
    display: flex;
    flex-wrap: wrap;
    width: 100%;
}


.customer-account-create .user-agreements-checkboxes .field, .customer-account-login .user-agreements-checkboxes .field {
    padding-right: 20px;
    font-size: 14px;
    margin: 0;
    position: relative;
    margin-bottom: 10px;
}

.user-agreements-checkboxes  {

    display: inline-flex;
    font-size: 14px;
    margin-bottom: -20px;
}

.user-agreements-checkboxes .field .label {
    display: inline-block;
    position: relative;
    height: 20px;
    padding-left: 25px;
    font-size: 12px;
    line-height: 20px;
    cursor: pointer;
    vertical-align: top;
    margin: 0;
}
.submit{
    width: 120px;
    margin-top: 20px;
    float: right;
}

    .agreement-block
    {
        height: 300px;
        overflow-y: scroll;
        margin-top: 20px;
        border: 1px solid #ccc;
        padding: 10px;
    }
    .agreement-title
    {
        margin-top: 40px;
        padding-bottom: 10px;
        border-bottom: 2px solid #000;
        font-size: 18px;
        font-weight: 700;
        color: #000;
        line-height: 1.36;
        display: block;
    }
</style>
<form class="form account form-create-account" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?php /* @noEscape */ echo $block->getBlockHtml('formkey'); ?>
    <div class=" create info">
        <fieldset>
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Personal Information') ?></span></legend>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
        <div class="field required">
            <div class="control">
                <input type="email" name="email" id="email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="field choice newsletter">
                <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                <label class="label"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?php echo $block->getChildHtml('customer.form.register.newsletter')?>
        <?php endif ?>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif ?>
        </fieldset>
    </div>
    <?php if ($block->getShowAddressFields()): ?>
        <div class=" address">
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address Information') ?></span></legend>
            <input type="hidden" name="create_address" value="1" />
            <div class="field company">
                <div class="control">
                    <input type="text" name="company" id="company" value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Company') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
                </div>
            </div>
            <div class="field telephone">
                <div class="control">
                    <input type="text" name="telephone" id="telephone" value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
                </div>
            </div>

            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

            <div class="field street required">
                <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
                <div class="control">
                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <div class="field additional">
                                <div class="control">
                                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Address') ?>" id="street_<?php /* @escapeNotVerified */ echo $_i ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field required">
                <div class="control">
                    <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
                <div class="control">
                    <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" style="display:none;">
                        <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                    </select>
                    <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Password *') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                </div>
            </div>

            <div class="field zip required">
                <div class="control">
                    <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" placeholder="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                </div>
            </div>

            <div class="field country required">
                <label for="country" class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
                <div class="control">
                    <?php echo $block->getCountryHtmlSelect() ?>
                </div>
            </div>
            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </div>

    <?php endif; ?>
    <div class=" create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <fieldset>
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Sign-in Information') ?></span></legend>

        <div class="field password required">
            <div class="control">
                <input type="password" name="password" id="password" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" class="input-text" placeholder="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}" autocomplete="off">
            </div>
        </div>
        <div class="field confirmation required">
            <div class="control">
                <input type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" placeholder="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
        </fieldset>
    </div>
    <?php if($_helper->getSystemConfig('integration', 'register')):?>
        <input style="float:left;margin: 0 10px 0 0;width:inherit;height:inherit" data-validate="{required:true}" type="checkbox" name="integration[register]"><?php echo $_helper->getSystemConfig('integration', 'register_text')?><br>
        <div id="register_integration_error" class="message info empty" style="display:none">
            <div><?php echo $_helper->getSystemConfig('integration', 'register_error')?></div>
        </div>
    <?php endif;?>

    <div class="user-agreements-checkboxes">
        <div class="field user-agreement required">
            <div class="control" style="float: left;">
                <input type="checkbox" name="user_agreement" id="user_agreement" value="1" title="<?= $block->escapeHtmlAttr(__('User Agreement')) ?>" class="input-text" data-validate="{required:true}">
            </div>
            <label class="label" for="user_agreement" style="float: right;">
                <span><?= $block->escapeHtml(__('User Agreement')) ?></span>
            </label>
        </div>

        <div class="field personal-info-usage required">
            <div class="control" style="float: left;">
                <input type="checkbox" name="personal_info_usage" id="personal_info_usage" value="1" title="<?= $block->escapeHtmlAttr(__('Usage of personal information')) ?>" class="input-text" data-validate="{required:true}">
            </div>
            <label class="label" for="personal_info_usage" style="float: right;">
                <span><?= $block->escapeHtml(__('Usage of personal information')) ?></span>
            </label>
        </div>
    </div>
    <div class="user-agreements-checkboxes">
        <div class="field email-receiving-agreement required">
            <div class="control" style="float: left;">
                <input type="checkbox" name="email_receiving_agreement" id="email_receiving_agreement" value="1" title="<?= $block->escapeHtmlAttr(__('Agreement on receiving emails')) ?>" class="input-text" data-validate="{required:true}">
            </div>
            <label class="label" for="email_receiving_agreement" style="float: right;">
                <span><?= $block->escapeHtml(__('Agreement on receiving emails')) ?></span>
            </label>
        </div>


        <div class="field sms-receiving-agreement required">
            <div class="control" style="float: left;">
                <input type="checkbox" name="sms_receiving_agreement" id="sms_receiving_agreement" value="1" title="<?= $block->escapeHtmlAttr(__('Agreement on receiving SMS')) ?>" class="input-text" data-validate="{required:true}">
            </div>
            <label class="label" for="sms_receiving_agreement" style="float: right;">
                <span><?= $block->escapeHtml(__('Agreement on receiving SMS')) ?></span>
            </label>
        </div>
    </div>



    <div class="user-agreements" style="margin-top: -70px;">
        <strong class="agreement-title">Terms of Use</strong>
        <div class="agreement-block">


            <?php echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('agreement_block')
                ->toHtml();
            ?>
        </div>
        <strong class="agreement-title">User Consent to Protect Personal Information</strong>
        <div class="agreement-block second">

            <?php echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('agreement_block_2')
                ->toHtml();
            ?>
        </div>
    </div>
    <div class="actions">
        <a class="action create" style="margin-top: 10px;font-size: 12px;" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></a>
        <button type="submit" class="btn action submit" title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></button>

    </div>

</form>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php if ($block->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>
<?php if($_helper->getSystemConfig('integration', 'register')):?>
    <script>
        require(['jquery'], function($){ 
            $(document).ready(function() {
                $("#form-validate").submit(function() {
                    if($('input[name="integration[register]"]').is(":checked")) {
                        $('#register_integration_error').hide();
                    } else {
                        $('#register_integration_error').show();
                    }
                });
            });
        });
    </script>
<?php endif;?>
