<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <div class="contact-content row">
			<div class="fix-width form-primary col-sm-12 col-md-8">
				<h2 class="regular-title"><?php echo __('Drop Us a line')?></h2>
				<fieldset class="fieldset">
					<div class="field name required">
						<label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
						<div class="control">
							<input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Your Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" placeholder="Your name(required)" type="text" data-validate="{required:true}"/>
						</div>
					</div>
					<div class="field whatisitabout required">
						<label for="email" class="required"><?php echo __('What is it about?') ?></label>
						<div class="input-box">
							<select name="whatisitabout" id="whatisitabout" title="<?php echo __('What is it about?') ?>">
								<!--<option>Enquiry/Questions</option>-->
								<option>My Order</option>
								<option>Other</option>
							</select>
						</div>
					</div>
					<div class="field email required">
						<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
						<div class="control">
							<input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Your Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" placeholder="Your email(required)" type="email" data-validate="{required:true, 'validate-email':true}"/>
						</div>
					</div>
					<div class="field telephone">
						<label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Telephone') ?></span></label>
						<div class="control">
							<input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Your Phone Number') ?>" value="" placeholder="Number Phone" class="input-text" type="text" />
						</div>
					</div>
					<div class="field comment required">
						<label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('Comment') ?></span></label>
						<div class="control">
							<textarea rows="10" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Your Message') ?>" placeholder="You comment(required)" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
						</div>
					</div>
					<?php echo $block->getChildHtml('form.additional.info'); ?>
					<div class="actions-toolbar">
						<div class="primary">
							<input type="hidden" name="hideit" id="hideit" value="" />
							<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
								<span><?php /* @escapeNotVerified */ echo __('Send Message') ?></span>
							</button>
						</div>
					</div>
				</fieldset>
			</div>  
			<div class="fix-width store-primary col-sm-12 col-md-4">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store-contact')->toHtml();?>
			</div>  	
    </div>
</form>
