<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<?php
$_helper = $this->helper('Mageplaza\SocialLogin\Helper\Config');
?>
<style>
.page-title-wrapper
{
    margn-top:-20px;
    font-size: 20px;
    text-align: center;
    padding-bottom: 22px;
    color: #000;
    font-size: 56px;
    font-weight: 500;
    border-bottom: 4px solid #000;
    text-align: center;
}
.login-input {
    max-width: 100%;
    margin-bottom:18px;
}
.block-content
{
    width:100%;
}

.form-login-style
{
    width: 80%;
    margin-top: 20px;
    margin-left: 70px;
}
.action
{
    float: left;
    margin-right: 50px;
    margin-top: 15px;
}
.block-new-customer
{
    padding-left: 69px;
}
</style>


<style>
    @media only screen and (min-device-width: 320px) {
        .form-login-style {
            width: 80%;
            margin-top: 20px;
            margin-left: 0px;
        }
    }


</style>
<div class="block-customer-login">
    <div class="block-content">
        <form class="form form-login form-login-style"
              action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <div class="login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <div class="email required">
                    <div class="control ">
                        <input class="login-input" name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" placeholder="<?php /* @escapeNotVerified */ echo __('Email *') ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="password required">
                    <div class="control">
                        <input class="login-input" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" placeholder="<?php /* @escapeNotVerified */ echo __('Password *') ?>" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <?php if($_helper->getSystemConfig('integration', 'login')):?>
                    <input style="float:left;margin: 0 10px 0 0;width:inherit;height:inherit" data-validate="{required:true}" type="checkbox" name="integration[login]"><?php echo $_helper->getSystemConfig('integration', 'login_text')?><br>
                    <div id="login_integration_error" class="message info empty" style="display:none">
                        <div><?php echo $_helper->getSystemConfig('integration', 'login_error')?></div>
                    </div>
                <?php endif;?>
                <p class="required" style="font-size: small;"><?php /* @escapeNotVerified */ echo __('* Required Fields'); ?></p>
                <table style="margin-left: -10px;">
                    <tr>
                        <td style="width:170px;"><button type="submit" class="btn action login" style="width: 160px;" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></td>
                    </tr>
                    <tr>
                        <td><a class="action remind forgot-pass"  href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span style="font-size: small;"><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></td>
                    </tr>
                </table>
            </div>


            </div><!----joinus_wrap end------>
        </form>
    </div>
</div>
<?php if($_helper->getSystemConfig('integration', 'login')):?>
    <script>
        require(['jquery'], function($){ 
            $(document).ready(function() {
                $("#login-form").submit(function() {
                    if($('input[name="integration[login]"]').is(":checked")) {
                        $('#login_integration_error').hide();
                    } else {
                        $('#login_integration_error').show();
                    }
                });
            });
        });
    </script>
<?php endif;?>
