<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
?>
<link
href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&subset=latin-ext"
rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Cairo:200,300,400,600,700,900&display=swap" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i&display=swap&subset=cyrillic,latin-ext,vietnamese"
rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Raleway:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&display=swap" rel="stylesheet">


<header class="page-header alothemes">
    <div class="header">
        <div class="header-top">
            <div class="container">
                <div class="top-bar-left">
                    <span><?php echo __('Welcome to Our LifeStyle Shop'); ?></span>
                </div>
                <div class="top-bar-right">
                    <div class="header-top-link">
                        <?php echo $this->getChildHtml('currency'); ?>
                        <?php echo $this->getChildHtml('store_language'); ?>
                        <div class="header-account">
                            <div class="toggle-tab">
                                <span><?php echo __("Account")?></span>                             
                                <span class="fa fa-angle-down" aria-hidden="true"></span>   
                            </div>
                            <div class="toggle-content">
                                <?php echo $this->getChildHtml('header.links'); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="menu-mobile header-sticker">
            <div class="container">
                <div class="header-content ">
                    <div class="header-logo">
                        <?php echo $this->getChildHtml('logo'); ?>
                    </div>
                    <div class="header-right">
                        <?php echo $this->getChildHtml('catalog.topnav'); ?>
                        <?php echo $this->getChildHtml('navigation.sections'); ?>
                        <?php echo $this->getChildHtml('minicart'); ?>
                    </div>
                </div>
            </div>
        </div>
    </header>